### ISSUE TITLE
feature_request add a Docker-Compose

### ISSUE THREAD

**Issue by LostOnTheLine** [luolongfei/freenom#195]
**Is your feature request related to a problem? Please describe.**
This is in English, but I'm sure you can translate it
I have a `docker-compose.yaml` that I created to run this & thought I'd share it. I included all the variables listed but they are commented out so you only have to enable the ones you want

With this you can easily deploy with Portainer or with a `docker-compose.yaml` file

```yaml
version: "3"
services:
  freenom:
    image: luolongfei/freenom:latest
    container_name: freenom
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Cancun
      #- RUN_AT="11:24"
      - FREENOM_USERNAME=''
      - FREENOM_PASSWORD=''
      #- MULTIPLE_ACCOUNTS=''                        # Support for multiple accounts '<account1>@<password1>|<account2>@<password2>|<account3>@<password3>' don't omit the "<>"
     # - FREENOM_PROXY=''                            # [Optional] Freenom proxy
      
# ###################### Notification email ######################### ## Robot mailbox account Email of robot
      #- MAIL_USERNAME=''                            # Robot mailbox account
      #- MAIL_PASSWORD=''                            # Robot email password
      #- TO=''                                       # Email to receive notifications Email
      #- MAIL_ENABLE=0                               # DEFAULT[0] - CHOICES: "1"=Enable email push features | "0": not enabled
      #- MAIL_HOST=''                                # [Optional] SMTP server eg smtp.gmail.com
      #- MAIL_PORT=''                                # [Optional] SMTP port number, usually "587" or "465"
      #- MAIL_ENCRYPTION=''                          # [Optional] Mail encryption method, usually "tls" or "ssl" or "starttls"
# ##################### Telegram bot ######################### ## Send notification messages via Telegram bot
      #- TELEGRAM_CHAT_ID=''                         # Your chat_id, you can get your own id by sending "/start" to @userinfobot
      #- TELEGRAM_BOT_TOKEN=''                       # Your Telegram bot token
      #- TELEGRAM_PROXY=''                           # [Optional] Telegram proxy eg http://127.0.0.1:1081 or socks5://127.0.0.1:1080
      #- CUSTOM_TELEGRAM_HOST='api.telegram.org'     # [Optional] Self-built Telegram reverse proxy address, please ignore this configuration item if you don’t understand it
      #- TELEGRAM_BOT_ENABLE=0                       # DEFAULT[0] - CHOICES: "1"=enable Telegram Bot features | "0": not enabled
# ###################### Enterprise WeChat ######################## ##
      #- WECHAT_CORP_ID=''                           # 企业IDCorporate ID
      #- WECHAT_CORP_SECRET=''                       # Credential keys for enterprise WeChat applications
      #- WECHAT_AGENT_ID=''                          # Application ID
      #- WECHAT_ENABLE=0                             # DEFAULT[0] - CHOICES: "1"=enable enterprise WeChat message push function | "0": not enabled
# ###################### Server Sauce##########################
      #- SCT_SEND_KEY=''                             # Server Sauce's SendKey
      #- SCT_ENABLE=0                                # DEFAULT[0] - CHOICES: "1"=enable Server Chan message function | "0": not enabled
# ##################### Send Bark ########################## Open the Bark App, register the device and see the key
      #- BARK_KEY=''                                 # Support direct paste "https://api.day Change .app/xxx/ here to your own push content" will automatically extract valid Bark key from it
      #- BARK_URL='https://api.day.app'              # The Bark URL defaults to the server provided by the Bark author, and it is recommended to build your own
      #- BARK_IS_ARCHIVE=''                          # # Bark Other related parameters (just keep the default)
      #- BARK_GROUP='FreeNom'
      #- BARK_LEVEL='active'
      #- BARK_ICON='https://q2.qlogo.cn/headimg_dl?dst_uin=593198779&spec=100'
      #- BARK_JUMP_URL=''
      #- BARK_SOUND='gotosleep'
      #- BARK_ENABLE=0                               # DEFAULT[0] - CHOICES: "1":enable Bark push messaging | "0": not enabled
######################  Pushplus  #########################
      #- PUSHPLUS_KEY=''                             # Pushplus token
      #- PUSHPLUS_ENABLE=0                           # DEFAULT[0] - CHOICES: "1":enable the Pushplus message function | "0": not enabled

      #- NOTICE_FREQ=1                               # DEFAULT[1] - CHOICES: "0": Only when there is a renewal operation | "1": Each execution
      #- VERIFY_SSL=0                                # DEFAULT[0] - CHOICES: "1": verify the server certificate | "0": no verification
      #- DEBUG=0                                     # DEFAULT[0] - CHOICES: "1": Debug mode On | "0": Debug mode Off
      #- NEW_VERSION_DETECTION=1                     # DEFAULT[1] - CHOICES: "0": Off | "1": Push a message notification when a new version is found
      #- CUSTOM_LANGUAGE=zh                          # DEFAULT[zh] - CHOICES: "zh" (Chinese) | "en" (English)
      #- SHOW_SERVER_INFO=0                          # DEFAULT[0] - CHOICES: "1": display server information when sending messages | "0": Do not display
      #- MOSAIC_SENSITIVE_INFO=0                     # DEFAULT[0] - CHOICES: "1": obfuscation of sensitive information | "0": Not enabled
    volumes:
      - /docker/nginx/freenom/conf:/conf
      - /docker/log/freenom:/app/logs:rw
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```
