### ISSUE TITLE
可以尝试一下使用github action、heroku app或者cloudflare workers

### ISSUE THREAD

**Issue by Galaxy-Studio-Code** [luolongfei/freenom#27]
本人是有服务器的，但似乎电报群里有很多人没有vps也希望使用，所以可以试试使用github action、heroku app或者cloudflare workers实现功能

**Comment by luolongfei** [comment]
github action没用过，不太了解，感觉像是类似自动化部署的东西；heroku app我记得是会自动休眠，而且重启后数据会全丢；cloudflare workers并不支持php，等star破千可以考虑看能不能写个node.js版本放cloudflare workers。

**Comment by Galaxy-Studio-Code** [comment]
嗯，workers.dev不太稳定，其实github pages也支持php

**Comment by Galaxy-Studio-Code** [comment]
期待楼主star过千

**Comment by luolongfei** [comment]
@Galaxy-Studio-Code github pages是静态网页托管，理论上不支持php，怎么看出支持的

**Comment by Galaxy-Studio-Code** [comment]
额，github action是支持的，github pages似乎不行，github actions文档里写了可以用php

**Comment by luolongfei** [comment]
@Galaxy-Studio-Code 你有使用github actions成功搭建php环境的实例吗

**Comment by Galaxy-Studio-Code** [comment]
实例我没有写过，但是yaml是这么配置的
```yaml
name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run
      run: ……
```
