### ISSUE TITLE
麻烦增加个自动同步的GitHub Actions

### ISSUE THREAD

**Issue by tanzl** [luolongfei/freenom#88]
**Is your feature request related to a problem? Please describe.**
麻烦加个自动同步的GitHub Actions吧

**Describe the solution you'd like**

**Describe alternatives you've considered**
https://github.com/marketplace/actions/github-repo-sync

**Additional context**

**Comment by luolongfei** [comment]
具体是做什么用的？

**Comment by tanzl** [comment]
就是Fork你的仓库之后通过GitHub Actions与你的仓库保持最新版本!

`repo-sync.yml`

```
# File: .github/workflows/repo-sync.yml
# ${{ secrets.PAT }}：Settings > Developer settings > Personal access tokens > Generate new token > 勾上workflow

name: repo-sync
on:
  workflow_dispatch:
  schedule:
    - cron: '10 23 * * *' # 东八区早上7点10分

jobs:
  repo-sync:
    if: ${{ github.repository != 'luolongfei/freenom' }}
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: 【同步luolongfei/freenom】
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/luolongfei/freenom.git"
          source_branch: "master"
          destination_branch: "master"
          sync_tags: "true"
          github_token: ${{ secrets.PAT }}
```
